test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.577028b4fb1afd20e26cb79af4fb3abe7d358790.name = "Upgrade from 1.4.1"
