test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f0329d9a.name = "Upgrade from 1.3.0"
