#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

timezone=$(timedatectl show --value --property=Timezone)
ynh_app_setting_set --key=php_upload_max_filesize --value=50M

#=================================================
# CREATE A MYSQL DATABASE
#=================================================

ynh_mysql_db_shell <<< "CREATE TABLE hm_user_session (hm_id varchar(180), data longblob, date timestamp, primary key (hm_id));"
ynh_mysql_db_shell <<< "CREATE TABLE hm_user (username varchar(250), hash varchar(250), primary key (username));"
ynh_mysql_db_shell <<< "CREATE TABLE hm_user_settings(username varchar(250), settings longblob, primary key (username));"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL CYPHT WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_exec install --no-dev --ignore-platform-reqs

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# ADD AN ADMIN USER
#=================================================
ynh_script_progression "Adding an admin..."

#Generate the run-time configuration
php$php_version $install_dir/scripts/config_gen.php

# create an admin account
php$php_version $install_dir/scripts/create_account.php $admin $password

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
